### ISSUE TITLE
Error: Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by kaicataldo** [dependents/atom-dependents#19]
![screen shot 2016-06-22 at 4 32 46 pm](https://cloud.githubusercontent.com/assets/7041728/16282504/02f8401c-3897-11e6-860c-aafb197d91ca.png)

I saw this error happen when I tried installing on two different machines. Clicking the "Rebuild Packages" button seems to resolve the issue, but I wonder if `apm` has the wrong version cached/packaged or something?

**Comment by mrjoelkemp** [comment]
Thanks for reporting. Seems like this is a known issue: https://github.com/atom/atom/issues/8837. Not sure there's much that I can do. The package.json file doesn't contain any specifics on node versions. I'm also not committing built assets, so it builds on install.

Thankfully there's the "rebuild packages" workaround. Going to close as a wont-fix since it's out of my control. Thanks again for reporting.
